services:
  edigateway.api:
    image: edigateway.api
    build:
      context: .
      dockerfile: src/EDIGateway.API/Dockerfile

  edimonitor.api:
    image: edimonitor.api
    build:
      context: .
      dockerfile: src/EDIMonitor.API/Dockerfile

  edi-monitor-client:
    build:
      context: ./client/edi-monitor-client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - edigateway.api
      - edimonitor.api


